### ISSUE TITLE
Interface with Matlab 

### ISSUE THREAD

**Issue by ys7yoo** [ys7yoo/BrainCaffe#1]
These Makefile and Makefile.config were tested for building MatCaffe on OsX 10.11.6 (El Capitan) and Matlab 2016b and worked fine.

Tests are needed for Ubuntu.

**Comment by Hahnnz** [comment]
In Brain Server,
To Test and Study 'structured_feature_pose', I download Pose-v2 and build caffe 
in 'Pose-v2' directory as it use 'CAFFE' tool, which is renamed as 'caffe-multi.
I set linkage caffe with matlab done, and As following Steps to train their own model,
Data_prepare was run in matlab. and it works well and done.
but the problem is next step. the next step is Run "ConvertLMDB.sh" to generate LMDB data.
So when I tried it, the error was emerged. error code is attached below.

(After prepared Data,)
$dash  ConvertLMDB.sh

I1109 19:17:34.473528 12863 convert_imageset.cpp:89] A total of 400 images.
F1109 19:17:34.474675 12863 db_lmdb.cpp:13] Check failed: mkdir(source.c_str(), 0744) == 0 (-1 vs. 0) mkdir ./cache/lsp/LMDB/LMDB_val_data failed
**\* Check failure stack trace: ***
    @     0x7ff63ec805cd  google::LogMessage::Fail()
    @     0x7ff63ec82433  google::LogMessage::SendToLog()
    @     0x7ff63ec8015b  google::LogMessage::Flush()
    @     0x7ff63ec82e1e  google::LogMessageFatal::~LogMessageFatal()
    @     0x7ff63f0340d0  caffe::db::LMDB::Open()
    @           0x403aaf  main
    @     0x7ff63dbf1830  __libc_start_main
    @           0x404b59  _start
    @              (nil)  (unknown)
Aborted (core dumped)
Traceback (most recent call last):
  File "./external/data/map2lmdb_datum.py", line 2, in <module>
    import skimage.io as io
ImportError: No module named skimage.io
Traceback (most recent call last):
  File "./external/data/map2lmdb_datum.py", line 2, in <module>
    import skimage.io as io
ImportError: No module named skimage.io
I1109 19:17:35.659976 12875 convert_imageset.cpp:89] A total of 81036 images.
F1109 19:17:35.660220 12875 db_lmdb.cpp:13] Check failed: mkdir(source.c_str(), 0744) == 0 (-1 vs. 0) mkdir ./cache/lsp/LMDB/LMDB_train_data failed
**\* Check failure stack trace: ***
    @     0x7faf3e6475cd  google::LogMessage::Fail()
    @     0x7faf3e649433  google::LogMessage::SendToLog()
    @     0x7faf3e64715b  google::LogMessage::Flush()
    @     0x7faf3e649e1e  google::LogMessageFatal::~LogMessageFatal()
    @     0x7faf3e9fb0d0  caffe::db::LMDB::Open()
    @           0x403aaf  main
    @     0x7faf3d5b8830  __libc_start_main
    @           0x404b59  _start
    @              (nil)  (unknown)
Aborted (core dumped)
Traceback (most recent call last):
  File "./external/data/map2lmdb_datum.py", line 2, in <module>
    import skimage.io as io
ImportError: No module named skimage.io
Traceback (most recent call last):
  File "./external/data/map2lmdb_datum.py", line 2, in <module>
    import skimage.io as io
ImportError: No module named skimage.io

it requires to find this file is for what and needs to dig out that file's code.

http://www.ee.cuhk.edu.hk/~xgwang/projectpage_structured_feature_pose.html
